### ISSUE TITLE
How do i connect my app to fitbit through oauth.

### ISSUE THREAD

**Issue by ghost** [manishkbharti/grailsOauthPluginDemo#5]
# I din't find my redirect url----

https://localhost:8080/VaporWire/my/showUserInfo/my/getUserDetails?completeAuthorization=&oauth_token=e8f7967f1d342adfba3bd1c21e533bb3&oauth_verifier=ocmmv1fslbqunapiphk6moi8d3

In this url basicaly there are two times controler and actions are in the url so how can i correct and build .....

**Comment by manishkbharti** [comment]
Hi @samirJft 
This question is not related to this repository. And Information you proviced is not sufficient to find the issue. 
It is better if you upload you code in a repository and ask your question in fitbit form or in Stackoverflow with relevant information.
Thanks
